### ISSUE TITLE
Heroku-22 and no system Ruby

### ISSUE THREAD

**Issue by edmorley** [siassaj/heroku-buildpack-git-deploy-keys#10]
Hi!

The Heroku-22 stack was just released:
https://devcenter.heroku.com/changelog-items/2429

In Heroku-22, there is no longer a system install of Ruby:
https://devcenter.heroku.com/articles/heroku-22-stack#system-ruby-is-no-longer-installed

This buildpack is written entirely in Ruby, and so in order for this buildpack to work on Heroku-22, one of the following will be necessary:
1. Have the buildpack vendor Ruby for use by this script (for an example of a buildpack doing this, see https://github.com/heroku/heroku-buildpack-nginx/pull/103).
2. Convert the buildpack to use shell/bash scripts instead.
3. Have users of this buildpack add the `heroku/ruby` buildpack prior to this one (they will also need to add a minimal `Gemfile` to their app source, if not already present, so the Ruby buildpack passes detection).

**Comment by siassaj** [comment]
@edmorley why u do this, don't you know i'm 35 & cranky now - get off my lawn
