### ISSUE TITLE
Not working with heroku-16 stack

### ISSUE THREAD

**Issue by Konkrad** [siassaj/heroku-buildpack-git-deploy-keys#7]
Hello,
thanks for the useful buildpack. Unfortunately, it stopped working for me suddenly. My assumption is that it has to do with the new introduced heroku-16 stack. Worked fine with the cedar-14 stack.

With the heroku-16 stack, I always get the error ```!!!! GIT_DEPLOY_KEY was invalid``` even though there is a valid key within the environment variable

**Comment by siassaj** [comment]
Hey Konkrad.
I haven't used heroku in about a year so I'm not sure, but I'll see about getting it fixed.

**Comment by siassaj** [comment]
@Konkrad hey I made some changes, I think it should work. But i only ran this against the buildpack tester and I'm not using it atm, can you give it a go?

**Comment by Konkrad** [comment]
Works like a charm! Thanks a lot
